-- -----------------------------------------------------
-- Table `full-stack-ecommerce`.`countries`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `full-stack-ecommerce`.`states`;
DROP TABLE IF EXISTS `full-stack-ecommerce`.`countries`;
CREATE TABLE IF NOT EXISTS `full-stack-ecommerce`.`countries`(
	`id` INT NOT NULL AUTO_INCREMENT,
    `code` CHAR(2) NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    PRIMARY KEY(`id`)
)
ENGINE=InnoDB
AUTO_INCREMENT=1;

-- -----------------------------------------------------
-- Table `full-stack-ecommerce`.`states`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `full-stack-ecommerce`.`states`(
	`id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `country_id` INT NOT NULL,
    PRIMARY KEY(`id`),
    CONSTRAINT `fk_countires_states_country_id`
    FOREIGN KEY (`country_id`) REFERENCES `full-stack-ecommerce`.`countries`(`id`)
)
ENGINE=InnoDB
AUTO_INCREMENT=1;

-- -----------------------------------------------------
-- Populate Countries
-- -----------------------------------------------------
INSERT INTO `countries`(`code`, `name`) VALUES
('IN','India'),
('CA','Canada'),
('DE','Germany'),
('BR','Brazil'),
('TR','Turkey'),
('US','United States');

INSERT INTO `states`(name, country_id) VALUES
-- -----------------------------------------------------
-- Indian States
-- -----------------------------------------------------
('Andhra Pradesh',1),
('Arunachal Pradesh',1),
('Assam',1),
('Bihar',1),
('Chhattisgarh',1),
('Goa',1),
('Gujarat',1),
('Haryana',1),
('Himachal Pradesh',1),
('Jammu & Kashmir',1),
('Jharkhand',1),
('Karnataka',1),
('Kerala',1),
('Madhya Pradesh',1),
('Maharashtra',1),
('Manipur',1),
('Meghalaya',1),
('Mizoram',1),
('Nagaland',1),
('Odisha',1),
('Punjab',1),
('Rajasthan',1),
('Sikkim',1),
('Tamil Nadu',1),
('Telangana',1),
('Tripura',1),
('Uttar Pradesh',1),
('Uttarakhand',1),
('West Bengal',1),
('Andaman and Nicobar Islands',1),
('Chandigarh',1),
('Dadra and Nagar Haveli',1),
('Daman & Diu',1),
('Lakshadweep',1),
('Puducherry',1),
('The Government of NCT of Delhi',1),


-- -----------------------------------------------------
-- Canada States
-- -----------------------------------------------------
('Alberta',2),
('British Columbia',2),
('Manitoba',2),
('New Brunswick',2),
('Newfoundland and Labrador',2),
('Northwest Territories',2),
('Nova Scotia',2),
('Nunavut',2),
('Ontario',2),
('Prince Edward Island',2),
('Quebec',2),
('Saskatchewan',2),
('Yukon',2),

-- -----------------------------------------------------
-- Germany States
-- -----------------------------------------------------
('Baden-Württemberg',3),
('Bavaria',3),
('Berlin',3),
('Brandenburg',3),
('Bremen',3),
('Hamburg',3),
('Hesse',3),
('Lower Saxony',3),
('Mecklenburg-Vorpommern',3),
('North Rhine-Westphalia',3),
('Rhineland-Palatinate',3),
('Saarland',3),
('Saxony',3),
('Saxony-Anhalt',3),
('Schleswig-Holstein',3),
('Thuringia',3),

-- -----------------------------------------------------
-- Brazil States
-- -----------------------------------------------------
('Acre',4),
('Alagoas',4),
('Amapá',4),
('Amazonas',4),
('Bahia',4),
('Ceará',4),
('Distrito Federal',4),
('Espírito Santo',4),
('Goiás',4),
('Maranhão',4),
('Mato Grosso do Sul',4),
('Mato Grosso',4),
('Minas Gerais',4),
('Paraná',4),
('Paraíba',4),
('Pará',4),
('Pernambuco',4),
('Piaui',4),
('Rio de Janeiro',4),
('Rio Grande do Norte',4),
('Rio Grande do Sul',4),
('Rondônia',4),
('Roraima',4),
('Santa Catarina',4),
('Sergipe',4),
('São Paulo',4),
('Tocantins',4),

-- -----------------------------------------------------
-- Turkey States
-- -----------------------------------------------------
('Adıyaman',5),
('Afyonkarahisar',5),
('Ağrı',5),
('Aksaray',5),
('Amasya',5),
('Ankara',5),
('Antalya',5),
('Ardahan',5),
('Artvin',5),
('Aydın',5),
('Balıkesir',5),
('Bartın',5),
('Batman',5),
('Bayburt',5),
('Bilecik',5),
('Bingöl',5),
('Bitlis',5),
('Bolu',5),
('Burdur',5),
('Bursa',5),
('Çanakkale',5),
('Çankırı',5),
('Çorum',5),
('Denizli',5),
('Diyarbakır',5),
('Düzce',5),
('Edirne',5),
('Elazığ',5),
('Erzincan',5),
('Erzurum',5),
('Eskişehir',5),
('Gaziantep',5),
('Giresun',5),
('Gümüşhane',5),
('Hakkâri',5),
('Hatay',5),
('Iğdır',5),
('Isparta',5),
('İstanbul',5),
('İzmir',5),
('Kahramanmaraş',5),
('Karabük',5),
('Karaman',5),
('Kars',5),
('Kastamonu',5),
('Kayseri',5),
('Kırıkkale',5),
('Kırklareli',5),
('Kırşehir',5),
('Kilis',5),
('Kocaeli',5),
('Konya',5),
('Kütahya',5),
('Malatya',5),
('Manisa',5),
('Mardin',5),
('Mersin',5),
('Muğla',5),
('Muş',5),
('Nevşehir',5),
('Niğde',5),
('Ordu',5),
('Osmaniye',5),
('Rize',5),
('Sakarya',5),
('Samsun',5),
('Siirt',5),
('Sinop',5),
('Sivas',5),
('Şanlıurfa',5),
('Şırnak',5),
('Tekirdağ',5),
('Tokat',5),
('Trabzon',5),
('Tunceli',5),
('Uşak',5),
('Van',5),
('Yalova',5),
('Yozgat',5),
('Zonguldak',5),

-- -----------------------------------------------------
-- US States
-- -----------------------------------------------------
('Alabama',6),
('Alaska',6),
('Arizona',6),
('Arkansas',6),
('California',6),
('Colorado',6),
('Connecticut',6),
('Delaware',6),
('District Of Columbia',6),
('Florida',6),
('Georgia',6),
('Hawaii',6),
('Idaho',6),
('Illinois',6),
('Indiana',6),
('Iowa',6),
('Kansas',6),
('Kentucky',6),
('Louisiana',6),
('Maine',6),
('Maryland',6),
('Massachusetts',6),
('Michigan',6),
('Minnesota',6),
('Mississippi',6),
('Missouri',6),
('Montana',6),
('Nebraska',6),
('Nevada',6),
('New Hampshire',6),
('New Jersey',6),
('New Mexico',6),
('New York',6),
('North Carolina',6),
('North Dakota',6),
('Ohio',6),
('Oklahoma',6),
('Oregon',6),
('Pennsylvania',6),
('Rhode Island',6),
('South Carolina',6),
('South Dakota',6),
('Tennessee',6),
('Texas',6),
('Utah',6),
('Vermont',6),
('Virginia',6),
('Washington',6),
('West Virginia',6),
('Wisconsin',6),
('Wyoming',6);